#ifndef _THROTTLER_IOCTL_H
#define _THROTTLER_IOCTL_H

#include <linux/ioctl.h>
#include <linux/types.h>

struct throttler_avg_data {
    unsigned long tot;
    unsigned long cnt;
};

struct throttler_peak_info {
    uid_t uid;
    char prog[16];
};

#define THROTTLER_IOC_MAGIC 'T'

#define THROTTLER_IOC_MONITOR_ON  _IO(THROTTLER_IOC_MAGIC, 1)
#define THROTTLER_IOC_MONITOR_OFF _IO(THROTTLER_IOC_MAGIC, 2)
#define THROTTLER_IOC_SET_MAX     _IOW(THROTTLER_IOC_MAGIC, 3, int)
#define THROTTLER_IOC_ADD_UID     _IOW(THROTTLER_IOC_MAGIC, 4, uid_t)
#define THROTTLER_IOC_ADD_SYSCALL _IOW(THROTTLER_IOC_MAGIC, 5, int)
#define THROTTLER_IOC_ADD_PROG    _IOW(THROTTLER_IOC_MAGIC, 6, char[16])
#define THROTTLER_IOC_REMOVE_UID     _IOW(THROTTLER_IOC_MAGIC, 7, uid_t)
#define THROTTLER_IOC_REMOVE_SYSCALL _IOW(THROTTLER_IOC_MAGIC, 8, int)
#define THROTTLER_IOC_REMOVE_PROG    _IOW(THROTTLER_IOC_MAGIC, 9, char[16])
#define THROTTLER_IOC_GET_PEAK_DELAY     _IOR(THROTTLER_IOC_MAGIC, 10, unsigned long)
#define THROTTLER_IOC_GET_BLOCKED_THREAD _IOR(THROTTLER_IOC_MAGIC, 11, int)
#define THROTTLER_IOC_GET_PEAK_DELAY_INFO _IOR(THROTTLER_IOC_MAGIC, 12, struct throttler_peak_info)
#define THROTTLER_IOC_GET_PEAK_BLOCKED    _IOR(THROTTLER_IOC_MAGIC, 13, int)
#define THROTTLER_IOC_GET_AVG_BLOCKED     _IOR(THROTTLER_IOC_MAGIC, 14, struct throttler_avg_data)
#define THROTTLER_IOC_GET_NUM_UIDS   _IOR(THROTTLER_IOC_MAGIC, 15, int)
#define THROTTLER_IOC_GET_UIDS       _IOR(THROTTLER_IOC_MAGIC, 16, uid_t*)
#define THROTTLER_IOC_GET_NUM_PROGS  _IOR(THROTTLER_IOC_MAGIC, 17, int)
#define THROTTLER_IOC_GET_PROGS      _IOR(THROTTLER_IOC_MAGIC, 18, char(*)[16])
#define THROTTLER_IOC_GET_SYSCALLS   _IOR(THROTTLER_IOC_MAGIC, 19, int*)
#define THROTTLER_IOC_GET_NUM_SYSCALLS   _IOR(THROTTLER_IOC_MAGIC, 20, int)

#endif
