#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/ioctl.h>
#include <string.h>
#include <pthread.h>
#include <sys/syscall.h>
#include <sys/prctl.h>
#include <time.h>

#include "../header/throttler_ioctl.h"

#define DEVICE_PATH "/dev/syscall_throttler"
#define SYSCALL_GETPID 39
#define DUMMY_UID 12345

#define MAX_TOKENS 5
#define NUM_THREADS 10
#define ITERATIONS  5

int fd;

struct thread_args {
    int id;
    int dummy_uid;
};

double get_elapsed_time(struct timespec start, struct timespec end) {
    return (end.tv_sec - start.tv_sec) + (end.tv_nsec - start.tv_nsec) / 1e9;
}

void* stress_worker(void* arg) {
    struct thread_args *t_arg = (struct thread_args *)arg;
    
    if (t_arg->dummy_uid) {
        syscall(SYS_setresuid, -1, DUMMY_UID, -1);
    }
    
    for (int i = 0; i < ITERATIONS; i++) {
        syscall(SYSCALL_GETPID);
    }
    
    printf("[Thread %02d] Finished its %d syscalls!\n", t_arg->id, ITERATIONS);
    return NULL;
}

void execute_stress_test(int dummy_uid) {
    struct timespec start, end;
    pthread_t *threads = malloc(NUM_THREADS * sizeof(pthread_t));
    struct thread_args *args = malloc(NUM_THREADS * sizeof(struct thread_args));

    if (!threads || !args) {
        perror("[-] Memory allocation error");
        exit(EXIT_FAILURE);
    }

    printf("[*] Launching %d threads...\n", NUM_THREADS);

    clock_gettime(CLOCK_MONOTONIC, &start);

    for (int i = 0; i < NUM_THREADS; i++) {
        args[i].id = i;
        args[i].dummy_uid = dummy_uid;
        pthread_create(&threads[i], NULL, stress_worker, &args[i]);
    }

    for (int i = 0; i < NUM_THREADS; i++) {
        pthread_join(threads[i], NULL);
    }

    clock_gettime(CLOCK_MONOTONIC, &end);
    double elapsed = get_elapsed_time(start, end);

    printf("\n[*] All threads broke through the barrier and finished in %.9f seconds.\n\n", elapsed);

    free(threads);
    free(args);
}

void print_statistics() {
    unsigned long peak_delay = 0;
    struct throttler_peak_info peak_info;
    memset(&peak_info, 0, sizeof(peak_info));
    int peak_blocked = 0;
    struct throttler_avg_data avg_data = {0, 0};

    ioctl(fd, THROTTLER_IOC_GET_PEAK_DELAY, &peak_delay);
    ioctl(fd, THROTTLER_IOC_GET_PEAK_DELAY_INFO, &peak_info);
    ioctl(fd, THROTTLER_IOC_GET_PEAK_BLOCKED, &peak_blocked);
    ioctl(fd, THROTTLER_IOC_GET_AVG_BLOCKED, &avg_data);

    double average_blocked = (avg_data.cnt == 0) ? 0.0 : ((double)avg_data.tot / avg_data.cnt);

    printf("[*] Statistics:\n");
    printf("Absolute peak delay: %lu ns (%.2f ms)\n", peak_delay, peak_delay / 1000000.0);
    if (peak_delay > 0) {
        printf("Generated by (Peak Info): Prog: %s, UID: %u\n", peak_info.prog, peak_info.uid);
    }
    printf("Peak simultaneous blocked threads: %d\n", peak_blocked);
    printf("Statistical avg. blocked threads: %.2f\n\n", average_blocked);
}

int main() {
    char prog_name[16];
    int max_val = MAX_TOKENS;
    int sys_target = SYSCALL_GETPID;
    uid_t dummy = DUMMY_UID;

    printf("=== Syscall Throttler Test ===\n\n");

    fd = open(DEVICE_PATH, O_RDWR);
    if (fd < 0) {
        perror("[-] ERROR: Unable to open /dev/syscall_throttler");
        return EXIT_FAILURE;
    }

    prctl(PR_GET_NAME, prog_name, 0, 0, 0);

    printf("[*] Configuring the module...\n");
    ioctl(fd, THROTTLER_IOC_SET_MAX, &max_val);
    ioctl(fd, THROTTLER_IOC_ADD_SYSCALL, &sys_target);
    printf("Limit %d syscalls/sec\n", max_val);
    printf("Hooked Syscall: %d\n\n", sys_target);


    printf("--- TEST 1A: Throttling on program ---\n");
    ioctl(fd, THROTTLER_IOC_ADD_PROG, prog_name);
    ioctl(fd, THROTTLER_IOC_MONITOR_ON);
    printf("Hooked program: '%s'\n", prog_name);
    printf("MONITOR ON!\n\n");
    
    execute_stress_test(0);
    print_statistics();

    ioctl(fd, THROTTLER_IOC_MONITOR_OFF);
    ioctl(fd, THROTTLER_IOC_REMOVE_PROG, prog_name);
    
    printf("--- TEST 1B: Program removed ---\n");
    ioctl(fd, THROTTLER_IOC_MONITOR_ON);
    printf("MONITOR ON! (But program is not in the list)\n\n");
    execute_stress_test(0);
    print_statistics();


    ioctl(fd, THROTTLER_IOC_MONITOR_OFF);
    
    printf("--- TEST 2A: Throttling on Dummy UID (%d) ---\n", dummy);
    ioctl(fd, THROTTLER_IOC_ADD_UID, &dummy);
    ioctl(fd, THROTTLER_IOC_MONITOR_ON);
    printf("Hooked UID: %d\n", dummy);
    printf("MONITOR ON!\n\n");
    
    execute_stress_test(1);
    print_statistics();

    ioctl(fd, THROTTLER_IOC_MONITOR_OFF);
    ioctl(fd, THROTTLER_IOC_REMOVE_UID, &dummy);
    
    printf("--- TEST 2B: UID removed (Unhooked) ---\n");
    ioctl(fd, THROTTLER_IOC_MONITOR_ON);
    printf("MONITOR ON! (But UID is not in the list)\n\n");
    execute_stress_test(1);
    print_statistics();

    ioctl(fd, THROTTLER_IOC_MONITOR_OFF);
    
    printf("--- TEST 3: Syscall disabled (Unhooked) ---\n");
    ioctl(fd, THROTTLER_IOC_ADD_PROG, prog_name);
    ioctl(fd, THROTTLER_IOC_REMOVE_SYSCALL, &sys_target);
    ioctl(fd, THROTTLER_IOC_MONITOR_ON);
    printf("Hooked program: '%s'\n", prog_name);
    printf("Syscall %d REMOVED from hooks!\n", sys_target);
    printf("MONITOR ON!\n\n");

    execute_stress_test(0);
    print_statistics();

    printf("[*] Cleaning up the environment...\n");
    ioctl(fd, THROTTLER_IOC_MONITOR_OFF);
    ioctl(fd, THROTTLER_IOC_REMOVE_PROG, prog_name);
    close(fd);

    printf("=== Test completed ===\n");
    return EXIT_SUCCESS;
}
